### ISSUE TITLE
Startup Issues

### ISSUE THREAD

**Issue by afgoody** [bsileo/SmartThings_Pentair#36]
Hello,
I think I've got everything configured properly except apparently the SmartThings port. On a Raspberry Pi 3 B+ using WiFi, when I try to start npm, it starts, but then outputs a bunch of ENOTFOUND errors (pasted below). Do I need to configure the json differently since I'm connected via WiFi instead of Ethernet?

Also, the SmartApp is not pulling in current information for sure, but last night it updated enough to pull in the system configuration allowing me to rename the child devices. However, if you look at the controller screenshot, you'll see it does not look right in a few places...and the data is very stale.

![smartthingspentairscreenshot](https://user-images.githubusercontent.com/46235745/52102758-17237580-2597-11e9-8e05-3cd0ebf06d51.jpg)

I appreciate any recommendations. Thank you...

    "integrations": {
        "outputToSmartThings": 1
    },
    "outputToSmartThings": {
        "address": "*",
        "port": "39500"
    }
}
20:11:25.973 INFO Starting up SSDP server
20:11:26.309 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:11:26.316 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:11:26.323 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:11:26.329 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:11:26.333 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:11:26.511 INFO Queueing messages to retrieve configuration from Intellitouch
20:11:26.584 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:11:26.657 WARN Update available!  Version 5.3.0 can be installed.  You have 5.2.0
20:11:26.661 WARN Update available!  Version 5.3.0 can be installed.  You have 5.2.0
20:11:27.098 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:11:29.407 INFO
  Custom Circuit Names retrieved from configuration:
        ["USERNAME-01","USERNAME-02","USERNAME-03","USERNAME-04","USERNAME-05","USERNAME-06","USERNAME-07","USERNAME-08","USERNAME-09","USERNAME-10"]
20:11:35.760 INFO
  Circuit Array Discovered from configuration:
Circuit 1: SPA Function: Spa Status: 0 Freeze Protection: off Macro: 0
Circuit 2: SLIDE Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 3: POOL LIGHT Function: Light Status: 0 Freeze Protection: off Macro: 0
Circuit 4: SPA LIGHT Function: Light Status: 0 Freeze Protection: off Macro: 0
Circuit 5: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 6: POOL Function: Pool Status: 0 Freeze Protection: off Macro: 0
Circuit 7: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 8: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 9: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 10: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 11: CLEANER Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 12: NOT USED Function: Not Used Status: 0 Freeze Protection: off Macro: 0
Circuit 13: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 14: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 15: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 16: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 17: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 18: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 19: NOT USED Function: Generic Status: 0 Freeze Protection: off Macro: 0
Circuit 20: SPILLWAY Function: Spillway Status: 0 Freeze Protection: off Macro: 0

20:11:35.822 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:11:35.995 INFO Msg# 45:  Intellibrite All On/Off and Light positions discovered:
POOL LIGHT: Position 1
SPA LIGHT: Position 1

20:11:36.006 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:11:38.689 INFO Msg# 58  Schedules discovered:
ID: 1  CIRCUIT:(11)CLEANER  MODE:Schedule START_TIME:3:00 END_TIME:06:00 DAYS:Sunday Monday Tuesday Wednesday Thursday Friday Saturday
ID: 2  CIRCUIT:(1)SPA  MODE:Egg Timer DURATION:2:0
ID: 3  CIRCUIT:(6)POOL  MODE:Schedule START_TIME:0:00 END_TIME:06:00 DAYS:Sunday Monday Tuesday Wednesday Thursday Friday Saturday
ID: 4  CIRCUIT:(12)NOT USED
ID: 5  CIRCUIT:(3)POOL LIGHT  MODE:Schedule START_TIME:18:00 END_TIME:20:00 DAYS:Sunday Friday Saturday
ID: 6  CIRCUIT:(2)SLIDE  MODE:Egg Timer DURATION:2:0
ID: 7  CIRCUIT:(3)POOL LIGHT  MODE:Egg Timer DURATION:3:0
ID: 8  CIRCUIT:(4)SPA LIGHT  MODE:Egg Timer DURATION:3:0
ID: 9  CIRCUIT:(11)CLEANER  MODE:Egg Timer DURATION:3:0
ID:10  CIRCUIT:(4)SPA LIGHT  MODE:Schedule START_TIME:18:00 END_TIME:20:00 DAYS:Sunday Friday Saturday
ID:11  CIRCUIT:(12)NOT USED
ID:12  CIRCUIT:(20)SPILLWAY  MODE:Egg Timer DURATION:3:0

20:11:38.931 INFO Discovered pump configurations: {
  "1": {
    "type": "VS",
    "circuit_slot": {
      "1": {
        "number": 6,
        "name": "POOL",
        "friendlyName": "POOL",
        "flag": "rpm",
        "rpm": 1500
      },
      "2": {
        "number": 20,
        "name": "SPILLWAY",
        "friendlyName": "SPILLWAY",
        "flag": "rpm",
        "rpm": 1600
      },
      "3": {
        "number": 11,
        "name": "CLEANER",
        "friendlyName": "CLEANER",
        "flag": "rpm",
        "rpm": 1700
      },
      "4": {
        "number": 2,
        "name": "SLIDE",
        "friendlyName": "SLIDE",
        "flag": "rpm",
        "rpm": 2600
      },
      "5": {
        "number": 1,
        "name": "SPA",
        "friendlyName": "SPA",
        "flag": "rpm",
        "rpm": 3200
      },
      "6": {
        "number": 0,
        "name": "none",
        "friendlyName": "none",
        "flag": "rpm",
        "rpm": 3000
      },
      "7": {
        "number": 0,
        "name": "none",
        "friendlyName": "none",
        "flag": "rpm",
        "rpm": 1000
      },
      "8": {
        "number": 0,
        "name": "none",
        "friendlyName": "none",
        "flag": "rpm",
        "rpm": 1000
      }
    },
    "prime": {
      "primingMinutes": 1,
      "rpm": 3300
    }
  }
}
20:11:48.096 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:12:01.883 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:12:05.601 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:13:02.016 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:13:02.873 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:14:01.278 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:14:02.177 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:15:01.694 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:15:03.479 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:16:01.616 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:16:02.777 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:17:01.740 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:17:02.073 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:18:01.018 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}
20:18:01.342 ERROR
        {"message":"getaddrinfo ENOTFOUND * *:39500","stack":"Error: getaddrinfo ENOTFOUND * *:39500\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"*","host":"*","port":"39500"}

**Comment by afgoody** [comment]
I tried replacing the * in the address field of the config.json with the ip address of my SmartThings hub and things are starting to work, but as soon as my ST hub gets assigned a new IP address, I'll need to update it in the json. Any idea why the * isn't working?

The spa and outside temp icons still look strange.

Also, has anyone noticed that the pool and spa temps can be mismatched (e.g. in ScreenLogic), but they seem to always match in nodejs-poolController and the SmartApp? Is that intentional?

**Comment by afgoody** [comment]
tagyoureit suggested I use his outputToSmartThings.js file. It worked allowing me to set the address back to *.
