### ISSUE TITLE
Add color / program controls for Intelisync lights

### ISSUE THREAD

**Issue by bsileo** [bsileo/SmartThings_Pentair#9]

**Comment by tagyoureit** [comment]
FYI, this isn't 100% working yet in the poolController app.  See [issue 10](https://github.com/tagyoureit/nodejs-poolController/issues/10).  I have had some people come/go, but I only have incandescent so can't really test/finish this code without a willing tester.  

If anyone has any of the color lights, I'm happy to further code this out.  Until then, this should stay on the back burner.

**Comment by bsileo** [comment]
I do have the color Intellisync lights @tagyoureit so I can look at this. I will let you know when I get time ot look at this on the ST side.

**Comment by bsileo** [comment]
I got this traceback today when running nodejs-poolcontrol and trying to change colors on my Intelibrite lights @tagyoureit . This is my first attempt at working to gather information for [#10](https://github.com/tagyoureit/nodejs-poolController/issues/10)

`Unhandled rejection TypeError: Cannot read property '194' of undefined
    at Object.setControllerLightColor (/home/pi/poolController/nodejs-poolController/src/lib/equipment/circuit.js:527:145)
    at Object.process (/home/pi/poolController/nodejs-poolController/src/lib/comms/inbound/controller/96.js:31:27)
    at Object.processControllerPacket (/home/pi/poolController/nodejs-poolController/src/lib/comms/inbound/process-controller.js:125:45)
    at decode (/home/pi/poolController/nodejs-poolController/src/lib/comms/inbound/decode-helper.js:263:51)
    at Object.processChecksum (/home/pi/poolController/nodejs-poolController/src/lib/comms/inbound/decode-helper.js:301:13)
    at Object.iterateOverArrayOfArrays (/home/pi/poolController/nodejs-poolController/src/lib/comms/inbound/receive-buffer.js:117:44)
    at Object.push (/home/pi/poolController/nodejs-poolController/src/lib/comms/inbound/packet-buffer.js:35:35)
    at SerialPort.<anonymous> (/home/pi/poolController/nodejs-poolController/src/lib/comms/sp-helper.js:74:44)
    at emitNone (events.js:106:13)
    at SerialPort.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at SerialPort.Readable.push (_stream_readable.js:208:10)
    at binding.read.then (/home/pi/poolController/nodejs-poolController/node_modules/serialport/lib/serialport.js:374:10)
`

**Comment by tagyoureit** [comment]
I'll leave the same comment here I left on my Issues list... which command were you using when you got this error?
